{{- if .Values.minio.enabled }}
{{- $secretName := .Values.minio.secretName }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if not $existing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "zenml-stack.labels" . | nindent 4 }}
    app.kubernetes.io/name: minio
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ default (randAlphaNum 48) .Values.minio.rootPassword | quote }}
{{- end }}
{{- end }}
