{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    {{- include "zenml-stack.labels" . | nindent 4 }}
    app.kubernetes.io/name: minio
spec:
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: s3
      port: 9000
      targetPort: s3
{{- end }}
