{{- if and .Values.registry.enabled .Values.registry.createPullSecret .Values.registry.dockerPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.pullSecretName }}
  labels:
    {{- include "zenml-stack.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        {{ .Values.registry.dockerServer | quote }}: {
          "username": {{ .Values.registry.dockerUsername | quote }},
          "password": {{ .Values.registry.dockerPassword | quote }},
          "auth": {{ printf "%s:%s" .Values.registry.dockerUsername .Values.registry.dockerPassword | b64enc | quote }}
        }
      }
    }
{{- end }}
