apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zenml-stack.orchestratorServiceAccount" . }}
  labels:
    {{- include "zenml-stack.labels" . | nindent 4 }}
    app.kubernetes.io/name: orchestrator
