{{- $password := include "zenml-server.databasePassword" . }}
{{- $rootPassword := include "zenml-server.databaseRootPassword" . }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.database.passwordSecretName }}
{{- if not $existing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.passwordSecretName }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  password: {{ $password | quote }}
  mysql-root-password: {{ $rootPassword | quote }}
{{- end }}
